### ISSUE TITLE
Introduce Notifications!

### ISSUE THREAD

**Issue by imath** [imath/bp-reactions#8]
I think it's a good idea, let's do this for next release!

See https://wordpress.org/support/topic/hi-imath?replies=1

**Comment by rvnamb** [comment]
I am really looking forward to this! :+1:   User notification for Likes and reactions is essential for great user experience

**Comment by imath** [comment]
I agree :) As soon as i've found some time, i'll work on it.

imath.
http://profiles.wordpress.org/imath/

**Comment by CeeGit** [comment]
Bonsoir mon cher iMath,
J'espère que tu vas bien. Toujours à la course pour la brioche ou plus de brioche?! 😉 Perso, j'ADORE ton plugin. Avoir par contre les connaissances pour le modifier, je ferais 2-3 trucs: 1- Il serait bien d'avoir l'option de mettre seulement 1icon ce qui permettrait qu'il soit positionné la où il y a le bouton pour ouvrir les réactions, un peu comme là où est le bouton Favori Ayant des connaissances en PHP et CSS et Jquery, je serais sûrement capable de le bidouiller un peu pour l'avoir comme tel à moins que je ne sois pas le seul qui aimerait cette fonction. 2-C'est parfait que tu "reshare" l'update en y ajoutant une réaction, comme ton plugin Reshare le fait aussi, mais il serait TROP PARFAIT d'avoir ces fichus notifications, dans la barre d'admin et aussi par courriel, comme je l'ai tant attendu sur ton plugin Reshare 😉 En passant, c'est moi Wcee qui t'avais poussé à repousser tes limites sur ce plugin. 3- Pour terminer, je permettrais aux admin de modifier les notifications pour chaque réactions ainsi que le nom, dans mon cas j'en aurais besoin d'une seule, ex un Fav ou Recommander ou Liker. Tu serais trop faire de le modifier comme tel et je dirais même plus, ça devrait être intégré dans le core de bp. Merci beaucoup de ton temps pour la lecture de mon commentaire et en espérant voir bientôt ton plugin version Supercharge. Merci! Take care.

**Comment by CeeGit** [comment]
Rebonjour iMathi,

Merci pour le commit! Pour l'instant ce qu'il y aurait à améliorer (selon moi) serait d'y ajouter les réglages de notifications dans les réglages email de profil parce que je ne vois pas d'option pour permettre aux utilisateurs de ne pas recevoir de notification par courriel lorsqu'une réaction est sur un activity update. Ce n'est pas quelque chose qui me dérange vraiment par contre car n'ayant pas d'application native, la seule façon de savoir si on a reçu une notification si on est pas sur le site est par courriel, sauf que étant donné que tout le reste peut-être ajuster ça fait un peut weird que cette seule option ne puisse être paramétrée. L'autre chose que je détecte est que lorsque que j'appuie sur le bouton pour réagir à un update, un certain délai s'écoule avant que le panneau des boutons de réaction dessous s'ouvre. Si je compare avec le plugin Activity Reactions For Buddypress que j'avais d'installé avant,  il y a une grosse difference car celui-ci s'ouvre instantanément. Et pour terminer, il serait bien de pouvoir avoir les 10 derniers users à avoir réagi à l'update un peu comme le plugin précedemment mentionné le fait. Pour le reste ça fonctionne du feu de dieu! Un dernier truc avant de terminer, j'utilise présentement le plugin BP Home Master ainsi que Buddypress Followers qui me permettent d'avoir mes updates et commentaires personnels ainsi que ceux de mes followers sous un même onglet qui remplace le sitewide activity all tab et je me demandais s'il serait possible de voir un update qui dit qu'un des users que je follow a réagi à un update? Pour l'instant je vois ce genre d'update apparaître seulement lorsque je désactive ton plugin. En te remerciant encore pour ton temps!

**Comment by imath** [comment]
Hello,
Enrichir une extension se fait pas à pas :) Ce commit traite des notifications à l'écran et non des emails raison pour laquelle il n'y a pas d'option dans les réglages de l'utilisateur. Vérifions d'abord que ces "screen" notifications fonctionnent bien avant de passer au cas des notifications email. Merci pour le reste de tes suggestions. Je vais y réfléchir.

imath.
http://profiles.wordpress.org/imath/

**Comment by CeeGit** [comment]
D'accord, je comprends. Encore un gros merci pour ton temps et ton implication, c'est vraiment apprécié!
Le 7 févr. 2017 12:54 AM, imath <notifications@github.com> a écrit :Hello,
Enrichir une extension se fait pas à pas :) Ce commit traite des notifications à l'écran et non des emails raison pour laquelle il n'y a pas d'option dans les réglages de l'utilisateur. Vérifions d'abord que ces "screen" notifications fonctionnent bien avant de passer au cas des notifications email. Merci pour le reste de tes suggestions. Je vais y réfléchir.

imath.
http://profiles.wordpress.org/imath/
